### ISSUE TITLE
General comments before pulling into SparklingGraph

### ISSUE THREAD

**Issue by riomus** [mssemik/complex-algorithms#1]
1. There must be unit tests both for computations results and performance
2. All packages must be changed in order to follow SparklingGraph schemat
3. After previous points updated, the code must be moved into SparklingGraph fork and you will create a pull request
4. After pull request creation, Jenkins will build everything, do a quality (Codacy) and coverage (Codecov) check so you will be able to fix all issues

**Comment by mssemik** [comment]
Done, I think. Sources have been moved to https://github.com/mssemik/sparkling-graph repo.

**Comment by riomus** [comment]
If it is moved, feel free to create pull requests. After that Jenkins etc. will do code analysis
